mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include(('project.urls','project'), namespace = 'project')),
]

project/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    #home page for the posts app
    path('', views.home, name='home'),
    path('projects/', views.projects, name = 'projects'),
    path('about/', views.about, name = 'about'),
    path('test/', views.test, name='test'),
 	path('projects/<int:project_id>', views.detail, name='detail'),
]

project/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

def upload_location(instance, filename):
	filebase, extension = filename.split(".")
	return "%s/%s" %(instance.id, filename)

class Project(models.Model):
	name = models.CharField(max_length = 120)
	description = models.TextField()
	video = models.CharField(max_length = 1000)
	#image = models.ImageField(upload_to = upload_location, null=True, blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("project:detail", kwargs={"id":self.id})

project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse

# Create your views here.

def home(request): #list items
	return render(request, "home.html")

def about(request):
	return render(request, "about.html")

def projects(request):
	queryset_list = Project.objects.all()
	context = {
		"object_list":queryset_list,
	}
	return render(request, "project.html", context)

def test(request):
	return render(request, "test.html")
	
def detail(request, project_id):
	instance = get_object_or_404(Project, id=project_id)
	context = {
		"instance" : instance,
	}
	return render(request, "detail.html", context)

project/templates/about.html
{% extends "base.html" %}
{% block content %}
<div class ="container">
	
	<h1 class ="page-header" align ="center"><u>About Me</u></h1>
	
	<p class ="lead"><mark>The Warriors have spent an entire season telling us they were fine while showing us, repeatedly, they were bored and uninspired.</p></mark>
	<p><mark> Keep on waiting for the Golden State Warriors to flex. Keep on waiting for them to show how dominant a team can be when it has the greatest shooter ever, arguably the second-greatest shooter ever, one of the greatest scorers to ever lace them up and one of the most versatile and villainous big men. Keep on waiting for the spectacular, for the special. Because the invincible team many thought would show up for this repeat bid might not ever come. And it might not have to.</p></mark>

	<button class ="btn btn-default"><a href="{% url 'project:home' %}">Back</a></button>
</div>

{% endblock content %}

project/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}AlHasani{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link rel="stylesheet" href="{% static 'css/new-age.min.css' %}"> -->
    <link href="{%static 'css/the-big-picture.css' %}" rel="stylesheet">
    <style>{% block style %}{% endblock style %}</style>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <!-- <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a> -->
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'project:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">About Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'project:projects' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">عربي</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

project/templates/detail.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
	<!-- Header with Background Image -->
    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <iframe width="1100" height="400" src="https://www.youtube.com/embed/D6esTdOLXh4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        <div class="col-sm-8">
          <h2 class="mt-4">What We Do</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum.</p>
          <p>
            <a class="btn btn-primary btn-lg" href="#">Call to Action &raquo;</a>
          </p>
        </div>
        <div class="col-sm-4">
          <h2 class="mt-4">Contact Us</h2>
          <address>
            <strong>Start Bootstrap</strong>
            <br>3481 Melrose Place
            <br>Beverly Hills, CA 90210
            <br>
          </address>
          <address>
            <abbr title="Phone">P:</abbr>
            (123) 456-7890
            <br>
            <abbr title="Email">E:</abbr>
            <a href="mailto:#">name@example.com</a>
          </address>
        </div>
      </div>
      <!-- /.row -->

	<a href="{% url 'project:projects' %}" class="btn btn-info" role="button">Link Button</a>
</html>
{% endblock content %}


project/templates/home.html
{% extends "base.html" %}
{% block content %}
<body>
    <!-- Page Content -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h1 class="mt-5">Ahmed <br/> Al Hasani</h1>
            <p>Hello, I am a graduate student at the Univeristy of Colorado Boulder studying Computer Science Data Science and Engineering and Software Engineering</p>
          </div>
        </div>
      </div>
    </section>
</body>
{% endblock content %}

project/templates/project.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}{{block.super}} | Projects{% endblock %}

    <!-- Bootstrap core CSS -->
    <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- {% block css %}
    	<link href="css/project.css" rel="stylesheet">
    {% endblock %} -->
  </head>
3
  {% block content %}
  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h2 class="my-4">Page Heading
        <!-- <small>Secondary Text</small> -->
      </h2>
      {% for obj in object_list %}
      <!-- Project One -->
      <div class="row">
        <span class="col-md-7">
          	<!-- <a href="#">
            	<img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
          	</a> -->
            
            <iframe width="560" height="350" src="{{obj.video}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          
        </span>
        <span class="col-md-5">
          <h4 id = "project-title"><a href="{% url 'project:detail' obj.id %}">{{obj.name}}</a></h4>
          <p id = "project-paragraph">{{ obj.description }}</p>
          <!-- <p id = "project-paragraph">{{ obj.id }} -->
        </span>
      </div>
      <!-- /.row -->

      <hr>

      {% endfor %}

      <!-- Project Two -->
      <!-- <div class="row">
        <div class="col-md-7">
          <a href="#">
            <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
          </a>
        </div>
        <div class="col-md-5">
          <h4 id = "project-title">Project Two</h4>
          <p id = "project-paragraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
        </div>
      </div> -->
      <!-- /.row -->

      <hr>

      <!-- Pagination -->
      <!-- <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul> -->

    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>
{% endblock content %}

project/templates/test.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ahmed AlHasani</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link rel="stylesheet" href="{% static 'css/new-age.min.css' %}"> -->
    <link href="{%static 'css/the-big-picture.css' %}" rel="stylesheet">
    <style>{% block style %}{% endblock style %}</style>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <!-- <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a> -->
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <!-- Page Content -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h1 class="mt-5">Ahmed <br/> Al Hasani</h1>
            <p>Hello, I am a graduate student at the Univeristy of Colorado Boulder studying Computer Science Data Science and Engineering and Software Engineering</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>